### ISSUE TITLE
set_aircraft_state does not seem to fully update the aircraft state.

### ISSUE THREAD

**Issue by tomaso909** [usuaero/MachUpX#1]
I recently started playing a bit with the library. I might be doing something wrong but I found the following issue.

**Describe the bug**
Calling ``set_aircraft_state`` does not seem to have any effect on the resulting forces. It does, however, update the aircraft wireframe.

**To Reproduce**
In this example I use the base FlyingWing .json example file. I compute the aircraft forces at several pitch angles. Every iteration I call ``set_aircraft_state`` with a new pitch angle. Fz, FL and FD are plotted at the end, showing that there is no change as a function of pitch.

```python

import json

import machupX as MX
import matplotlib.pyplot as plt


if __name__=="__main__":

    input_file = "flying_wing_input.json"
    my_scene = MX.Scene(input_file)

    results = []
    pitches = range(30)

    for pitch in pitches:
        FM_results = my_scene.solve_forces(dimensional=True, non_dimensional=False, verbose=True)
        print(json.dumps(FM_results["flying_wing"]["total"], indent=4))

        newState = {
                    "type" : "aerodynamic",
                    "velocity" : 100,
                    "alpha" : 2.0,
                    "beta" : 0.0,
                    "orientation":[0,pitch,0]
                }
        my_scene.set_aircraft_state(newState,'flying_wing')

        results.append(FM_results["flying_wing"]["total"])

        # my_scene.display_wireframe(show_legend=True) # This actually displays the aircraft wireframe with the updated pitch.

    ax = plt.figure().gca()
    ax.plot(pitches,list(map(lambda x:x['Fz'],results)),'r-',label='Fz')
    ax.plot(pitches,list(map(lambda x:x['FL'],results)),'g-',label='FL')
    ax.plot(pitches,list(map(lambda x:x['FD'],results)),'b-',label='FD')
    ax.set_xlabel('Pitch')
    ax.set_ylabel('F')
    ax.grid()
    plt.show()
```

**Comment by tomaso909** [comment]
I just saw that there is a ```rigid-body``` state type. Using this one seems to produce the results I expect.
I guess that with the ```aerodynamic``` state type I'm fixing alpha to 2 degrees so changing the pitch has no effect on the angle of attack.

**Comment by corygoates** [comment]
@tomaso909 You're correct. When using the aerodynamic state type, alpha and beta define the freestream vector relative to the aircraft. So if you rotate the aircraft in pitch using orientation, this will rotate the freestream vector with it, preserving the defined values for alpha and beta.
