### ISSUE TITLE
Error Plotting Distributions

### ISSUE THREAD

**Issue by hughjward** [usuaero/MachUpX#2]
**Describe the bug**
The name of the airplane appears to be hard coded to "test_plane" in the 'distributions' function. 

Line 1727 of scene.py

**To Reproduce**
1. Run any of the examples
2. Run distributions function:

my_scene.distributions(filename='testplot1', make_plots=['cpx'])
Traceback (most recent call last):

  File "/MachUpX-1.0-py3.7.egg/machupX/scene.py", line 1727, in distributions
    for segment_name, segment_dist in dist["test_plane"].items():

KeyError: 'test_plane'

**Comment by corygoates** [comment]
@hughjward I am unable to reproduce your error with any of the example scripts. Please make sure you have the latest version downloaded and installed. If the issue persists, please include your full set of files necessary to reproduce the bug.

Thanks!

**Comment by hughjward** [comment]
Ah yes, I have only recently started using MachUpX, but it was installed the day before you fixed this bug!
