### ISSUE TITLE
aircraft_derivatives

### ISSUE THREAD

**Issue by bhogin** [usuaero/MachUpX#3]
MachUpX does not recognize aircraft_derivatives to be specified in the input .json file. Attempted traditional airplane example from repo: 

"aircraft_derivatives is not recognized as a valid run command. Skipping..." displayed in command line. 

Note: example has scene class of aero_derivatives. Based on the docs I believe it should be now aircraft_derivatives for v2.

**Comment by corygoates** [comment]
Could you point to where you found this described in the documentation? The "run" keys for the input file and the Scene class methods are described separately. It was a goal of Version 2 to make them the same, but other goals took priority. We will likely update this in the future, but for now, the documentation is accurate.

**Comment by bhogin** [comment]
Hello Cory, 

Thanks, I was referring to, under the scene page in the docs: 
<img width="664" alt="Screen Shot 2020-05-29 at 9 52 28 AM" src="https://user-images.githubusercontent.com/57079248/83284830-1eaa5d00-a192-11ea-88de-3e1843f8b9b5.png">

I now understand it is rather: 
<img width="606" alt="Screen Shot 2020-05-29 at 10 36 51 AM" src="https://user-images.githubusercontent.com/57079248/83288521-561c0800-a198-11ea-9522-9777cfa54a77.png">

This has resolved my problem. Thank you.
