### ISSUE TITLE
airfoils dependency incorrect version

### ISSUE THREAD

**Issue by afshawnlotfi** [usuaero/MachUpX#4]
**Describe the bug**
During installation ``pip install .``  throws
```
ERROR: Could not find a version that satisfies the requirement airfoil_db==1.4 (from MachUpX==2.3.4) (from versions: none)
ERROR: No matching distribution found for airfoil_db==1.4 (from MachUpX==2.3.4)
```
I narrowed it down because airfoil_db doesn't seem to be up on pip. I will just fork and get it straight from the Github package source.

**To Reproduce**
1. git clone https://github.com/usuaero/MachUpX
2. cd MachUpX
3. pip install .

**Expected behavior**
Install successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/6283745/87502483-a4de0e00-c62f-11ea-9eac-047c60b2f41f.png)

**Desktop (please complete the following information):**
- Docker Container: continuumio/anaconda3 - latest
- macOS 10.15.5 (19F101)

**Comment by corygoates** [comment]
I wouldn't consider this a bug because the need to install AirfoilDatabase before installing MachUpX is explained in the docs (https://machupx.readthedocs.io/en/latest/installation.html). I like your solution though and may include that in a future release.
